//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EP_1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPEntities : DbContext
    {
        public EPEntities()
            : base("name=EPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Concert> Concert { get; set; }
        public virtual DbSet<Organizer> Organizer { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Singer> Singer { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_of_concert> Type_of_concert { get; set; }
        public virtual DbSet<Type_of_music> Type_of_music { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
